name: Build APK

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Buildozer environment
      run: |
        sudo apt-get update
        sudo apt-get install -y git zip unzip openjdk-17-jdk python3-pip autoconf libtool pkg-config zlib1g-dev libncurses-dev libsdl2-dev libsdl2-image-dev libsdl2-mixer-dev libsdl2-ttf-dev
        pip3 install --user buildozer

    - name: Create buildozer.spec if not exists
      run: |
        if [ ! -f buildozer.spec ]; then
          ~/.local/bin/buildozer init
        fi

    - name: Build Android APK
      run: |
        ~/.local/bin/buildozer android debug
