name: Build Android APK (Full Auto Buildozer)

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            python3 python3-pip openjdk-17-jdk unzip zip wget git \
            libssl-dev libffi-dev build-essential libsqlite3-dev zlib1g-dev \
            autoconf automake libtool pkg-config \
            adb libncurses5 libncurses5-dev \
            ccache libstdc++6 libz1 gcc g++ \
            cmake make curl

      - name: Install Python dependencies (Buildozer, Cython)
        run: |
          pip3 install --upgrade pip setuptools wheel
          pip3 install --user buildozer cython

      - name: Setup environment
        run: |
          echo "$HOME/.local/bin" >> $GITHUB_PATH

      - name: Build APK with Buildozer
        run: |
          buildozer android clean
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
